// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TakeawayTitans.Data;

#nullable disable

namespace TakeawayTitans.Migrations
{
    [DbContext(typeof(TakeawayTitansContext))]
    [Migration("20251001130738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TakeawayTitans.Data.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Crisp romaine with Caesar dressing.",
                            ImageUrl = "https://example.com/caesar-salad.jpg",
                            Name = "Caesar Salad",
                            Price = 7.25m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tomatoes, cucumbers, feta, and olives.",
                            ImageUrl = "https://example.com/greek-salad.jpg",
                            Name = "Greek Salad",
                            Price = 7.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh mixed greens with seasonal veggies.",
                            ImageUrl = "https://example.com/garden-salad.jpg",
                            Name = "Garden Salad",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Baby spinach, strawberries, and almonds.",
                            ImageUrl = "https://example.com/spinach-salad.jpg",
                            Name = "Spinach Salad",
                            Price = 7.75m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chicken, bacon, avocado, egg, and blue cheese.",
                            ImageUrl = "https://example.com/cobb-salad.jpg",
                            Name = "Cobb Salad",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Fresh strawberries blended with yogurt.",
                            ImageUrl = "https://example.com/strawberry-smoothie.jpg",
                            Name = "Strawberry Smoothie",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ripe mangoes with orange juice.",
                            ImageUrl = "https://example.com/mango-smoothie.jpg",
                            Name = "Mango Smoothie",
                            Price = 5.75m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Banana, milk, and honey.",
                            ImageUrl = "https://example.com/banana-smoothie.jpg",
                            Name = "Banana Smoothie",
                            Price = 5.25m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Spinach, kale, apple, and banana.",
                            ImageUrl = "https://example.com/green-smoothie.jpg",
                            Name = "Green Smoothie",
                            Price = 6.00m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Mixed berries blended with yogurt.",
                            ImageUrl = "https://example.com/berry-blast-smoothie.jpg",
                            Name = "Berry Blast Smoothie",
                            Price = 6.25m
                        });
                });

            modelBuilder.Entity("TakeawayTitans.Data.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TakeawayTitans.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Customization")
                        .HasColumnType("text");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TakeawayTitans.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FName = "Alice",
                            LName = "Johnson",
                            Password = "password",
                            Type = "admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            FName = "Bob",
                            LName = "Smith",
                            Password = "password",
                            Type = "admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            FName = "Carol",
                            LName = "Davis",
                            Password = "password",
                            Type = "admin",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = 4,
                            FName = "David",
                            LName = "Martinez",
                            Password = "password",
                            Type = "admin",
                            Username = "admin4"
                        },
                        new
                        {
                            Id = 5,
                            FName = "Emma",
                            LName = "Wilson",
                            Password = "password",
                            Type = "admin",
                            Username = "admin5"
                        });
                });

            modelBuilder.Entity("TakeawayTitans.Data.Models.OrderItem", b =>
                {
                    b.HasOne("TakeawayTitans.Data.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TakeawayTitans.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TakeawayTitans.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
